language: cpp

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq cmake doxygen g++-4.8 python-pip cppcheck valgrind
    - sudo pip install Pygments
    - sudo pip install gcovr
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

compiler:
    - gcc

script: ./build.sh
