language: cpp
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen valgrind cppcheck gcovr
compiler:
  - gcc
#before_install:
# TODO install all required tools
script: ./build.sh
